from modelos.bitflip import bit_flip
from lectura import print_matrix
from modelos.isgoal import isgoal
import copy

def expand_node(matrix):
    hijos = []
    prox_hijo = []
    # loop through rows
    for i in range(16):
        # loop through columns 
        for j in range(16):
            # add each possible child generated by changing one cell
            matrix_copy = copy.deepcopy(matrix)
            hijos.append(bit_flip(matrix_copy, i, j))
    
    # return the list of all possible children of the current state
    return hijos