from modelos.bitflip import bit_flip
import copy

def expand_node(matrix):
    hijos = []
    # loop through rows
    for i in range(16):
        # loop through columns 
        for j in range(16):
            # add each possible child generated by changing one cell
            prox_hijo = bit_flip(matrix, i, j)
            hijos.append(prox_hijo)
            # print("next hijo\n")
            # print_matrix(prox_hijo)
            # print("\n")
    
    # return the list of all possible children of the current state
    return hijos